version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "/usr/local/bin/php /var/www/v1/worker.php"

http:
  pool:
    num_workers: 55
  address: "0.0.0.0:8080"
  middleware: [gzip] # otel middleware should be applied first in the line (from right to left). Middleware order is: `request` --> `otel` -> `gzip` -> `http-plugin` -> `PHP worker`.

logs:
  level: info
  output: stdout